spring:
  application:
    name: userAdvicesMariadb

  datasource:
    url: jdbc:mariadb://db:3306/useradvicesmariadb
    username: app_user
    password: app_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  mail:
    host: smtp4dev
    port: 25

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 458358804580-ldmiqvlig3bpnk3205kvidp9spg8ipb3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:9191/login/oauth2/code/google"
            client-name: Google
          facebook:
            client-id: facebook-client-id
            client-secret: facebook-client-secret
            scope:
              - public_profile
              - email
            redirect-uri: "http://localhost:9191/login/oauth2/code/facebook"
            client-name: Facebook
          github:
            client-id: Ov23likkwEWOdEQRFVKr
            client-secret: 52438dea155088efe044a172b9366d913619d2b4
            scope:
              - user:email
            redirect-uri: "http://localhost:9191/login/oauth2/code/github"
            client-name: GitHub
        provider:
          google:
            issuer-uri: https://accounts.google.com
          facebook:
            authorization-uri: https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

server:
  port: 9191
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: debug
